[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache = true
ffi = false
verbosity = 3
solc_version = '0.8.24'
evm_version = 'paris'
gas_reports = ["*"]
auto_detect_solc = false